export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#4cd7f6",
        secondary: "#ddb7ff",
        tertiary: "#ffb873",

        background: "#0e1416",
        surface: "#0e1416",

        "on-surface": "#dee3e6",
        "on-surface-variant": "#bcc9cd",

        "surface-container-low": "#171d1e",
        "surface-container-lowest": "#090f11",

        "primary-container": "#06b6d4",

        "on-primary": "#003640",
          primary: "#4cd7f6",
        "primary-container": "#06b6d4",
        secondary: "#ddb7ff",
        "on-primary": "#003640",
        "secondary-container": "#6f00be",
                    "on-primary-fixed-variant": "#004e5c",
                    "on-primary-fixed": "#001f26",
                    "tertiary-fixed": "#ffdcbf",
                    "surface-container-lowest": "#090f11",
                    "on-background": "#dee3e6",
                    "tertiary-container": "#e89337",
                    "surface-container-highest": "#303638",
                    "on-tertiary-fixed-variant": "#6a3b00",
                    "surface-container-high": "#252b2d",
                    "surface-variant": "#303638",
                    "tertiary-fixed-dim": "#ffb873",
                    "on-surface": "#dee3e6",
                    "on-error-container": "#ffdad6",
                    "primary": "#4cd7f6",
                    "on-surface-variant": "#bcc9cd",
                    "inverse-primary": "#00687a",
                    "on-primary": "#003640",
                    "primary-container": "#06b6d4",
                    "primary-fixed": "#acedff",
                    "surface-dim": "#0e1416",
                    "surface": "#0e1416",
                    "background": "#0e1416",
                    "outline-variant": "#3d494c",
                    "surface-bright": "#343a3c",
                    "inverse-surface": "#dee3e6",
                    "on-tertiary-container": "#5b3200",
                    "secondary-fixed": "#f0dbff",
                    "on-tertiary": "#4b2800",
                    "on-secondary-container": "#d6a9ff",
                    "inverse-on-surface": "#2b3133",
                    "error-container": "#93000a",
                    "on-secondary": "#490080",
                    "secondary-fixed-dim": "#ddb7ff",
                    "surface-container-low": "#171d1e",
                    "surface-tint": "#4cd7f6",
                    "on-error": "#690005",
                    "error": "#ffb4ab",
                    "surface-container": "#1b2122",
                    "on-secondary-fixed": "#2c0051",
                    "outline": "#869397",
                    "tertiary": "#ffb873",
                    "primary-fixed-dim": "#4cd7f6",
                    "on-secondary-fixed-variant": "#6900b3",
                    "secondary": "#ddb7ff",
                    "on-tertiary-fixed": "#2d1600",
                    "on-primary-container": "#00424f"
      }
    }
  },
  plugins: [],
}